In [1]:
import numpy as np

In [5]:
#CREAR UN ARREGLO DE UNA DIMENSION CON 6 ELEMENTOS
arr1 = np.array([1, 2, 3, 4, 5,6])
print("Arreglo de una dimension: ",arr1)
print("Forma del arreglo: ",arr1.shape)
print("Tipo de dato del arreglo: ",arr1.dtype)


Arreglo de una dimension:  [1 2 3 4 5 6]
Forma del arreglo:  (6,)
Tipo de dato del arreglo:  int64


In [9]:
# CAMBIAR LA FORMA DEL ARREGLO A UNA MATRIZ DE 2 FILAS Y 3 COLUMNA
arr2 = arr1.reshape(2, 3)
print("Arreglo de dos dimensiones:\n",arr2)
print("Forma del arreglo: ",arr2.shape)
print("Tipo de dato del arreglo: ",arr2.dtype)

Arreglo de dos dimensiones:
 [[1 2 3]
 [4 5 6]]
Forma del arreglo:  (2, 3)
Tipo de dato del arreglo:  int64


In [ ]:
#CREAR UNA MATRIZ DE 4 FILAS Y 4 COLUMNAS CON VALORES ALEATORIOS ENTRE 0 Y 1
arr3 = np.random.random((4, 4))
print("Matriz de 4 filas y 4 columnas con valores aleatorios entre 0 y 1:\n",arr3)
print("Forma del arreglo: ",arr3.shape) 

Matriz de 4 filas y 4 columnas con valores aleatorios entre 0 y 1:
 [[0.81400238 0.96719843 0.98530556 0.56001884]
 [0.46114513 0.57739612 0.32607671 0.13108007]
 [0.87786155 0.02642689 0.23354654 0.69608791]
 [0.35781446 0.77862039 0.50196675 0.50878366]]
Forma del arreglo:  (4, 4)


In [16]:
#MATRIZ CON VALORES ENTRE 5 Y 10
arr3 = np.random.uniform(5, 10, (4,4))

print("Matriz con valores entre 5 y 10:\n", arr3)
print("Forma del arreglo:", arr3.shape)
print("Tipo de dato del arreglo:", arr3.dtype)

Matriz con valores entre 5 y 10:
 [[9.70732143 8.84831733 6.11498515 8.02639029]
 [6.34511316 5.91071221 7.86968349 6.48131198]
 [8.22422852 9.48522735 6.16546088 6.56896473]
 [9.97605398 8.84286031 6.50125218 7.89599141]]
Forma del arreglo: (4, 4)
Tipo de dato del arreglo: float64


In [19]:
#CREA UN ARREGLO DE 2 DIM A PARTIR DE UNA LISTA DE LISTAS
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
#arr
print("Arreglo de 2 dimensiones:\n",arr)
print("Forma del arreglo: ",arr.shape)
print("Tipo de dato del arreglo: ",arr.dtype)
print(type(arr))

Arreglo de 2 dimensiones:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma del arreglo:  (3, 3)
Tipo de dato del arreglo:  int64
<class 'numpy.ndarray'>


In [22]:
arr_zero = np.zeros((3,3))
print("Arreglo de ceros:\n",arr_zero)
print("Forma del arreglo: ",arr_zero.shape)
print("Tipo de dato del arreglo: ",arr_zero.dtype)
arr_ones = np.ones((2,4))
arr_ones[1,1] = 5
print("Arreglo de unos:\n",arr_ones)
print("Forma del arreglo: ",arr_ones.shape)
print("Tipo de dato del arreglo: ",arr_ones.dtype)
arr_identity = np.eye(4)
print("Matriz identidad:\n",arr_identity)   
print("Forma del arreglo: ",arr_identity.shape)
print("Tipo de dato del arreglo: ",arr_identity.dtype)

Arreglo de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Forma del arreglo:  (3, 3)
Tipo de dato del arreglo:  float64
Arreglo de unos:
 [[1. 1. 1. 1.]
 [1. 5. 1. 1.]]
Forma del arreglo:  (2, 4)
Tipo de dato del arreglo:  float64
Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Forma del arreglo:  (4, 4)
Tipo de dato del arreglo:  float64


In [25]:
#CREAR ARREGLO 3D DE CEROS CON FORMA (2,3,4)
arr = np.zeros((2,3,4))
arr[0,1,2]= 7
arr[1,2,2]= 5
print("Arreglo 3D de ceros:\n",arr)

Arreglo 3D de ceros:
 [[[0. 0. 0. 0.]
  [0. 0. 7. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 5. 0.]]]
